SOURCE=utf16_lo.cpp  utf16_up.cpp  utf16win.cpp  win_dos.cpp  win_iso.cpp  win_koi.cpp  win_mac.cpp  chartype.cpp
OBJDIR=tmp/
OUTPUT=libcodes.a
OBJSET=$(addprefix $(OBJDIR), $(notdir $(SOURCE:.cpp=.o)))

$(OUTPUT): $(OBJSET)
	@ar -rc $@ $(OBJSET)

$(OBJSET): $(OBJDIR)

$(OBJDIR)%.o: %.cpp
	$(CC) -o $@ -c $<

$(OBJDIR):
	@mkdir -p $@

